[package]
name = "morph-config"
version = "0.1.0"
edition = "2021"
description = "Morph project configuration parsing"
license = "Apache-2.0"
repository = "https://github.com/Levizr/morph"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
semver = { workspace = true }

[lints]
workspace = true
