[build-system]
requires = ["setuptools>=61.0.0,<70", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "levizr-morph"
version = "0.0.6"
description = "Build native OpenGL Applications with HTML, CSS, and JavaScript"
license = {text = "Apache-2.0"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "watchdog>=6.0.0",
    "jinja2>=3.0",
    "click>=8.0",
    "tree-sitter>=0.25",
    "tree-sitter-typescript>=0.23",
    "tree-sitter-css>=0.25",
]
[tool.setuptools.packages.find]
include = ["morph*"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
morph = ["codegen/templates/*.j2"]

[project.urls]
Homepage = "https://github.com/levizr/morph"
Source = "https://github.com/levizr/morph"
BugTracker = "https://github.com/levizr/morph/issues"

[project.scripts]
morph = "morph.cli.main:main"

[project.optional-dependencies]
dev = ["pytest>=7.0", "pytest-cov"]
