"""C++/JSX interop codegen helpers.

Morph compiles .mx (JSX/TS) straight to C++, so there is no FFI — a user
`.cpp` file imported with `import {} from './native.cpp'` is #included into
the generated translation unit. This module generates the `_morph_state.h`
header that exposes morphState signals (as setters/getters) and JSX
functions to that user C++ code, and extracts function signatures from the
transpiled C++ so both directions can see each other.
"""
from __future__ import annotations

import re

# ── State var type inference (mirrors codegen/emitter + logic_emitter) ──


def cpp_type_from_init(init: str) -> str:
    raw = init.strip()
    if raw.startswith("'") and raw.endswith("'"):
        return "std::string"
    if raw in ("true", "false"):
        return "bool"
    if raw.startswith('"'):
        return "std::string"
    if "." in raw:
        return "double"
    if raw.isdigit() or (raw.startswith("-") and raw[1:].isdigit()):
        return "int"
    return "auto"


def clean_init(init: str) -> str:
    raw = init.strip()
    if raw.startswith("'") and raw.endswith("'"):
        return f'"{raw[1:-1]}"'
    return raw


def collect_state_vars(windows) -> list[dict]:
    """Deduplicated morphState definitions across all windows."""
    out: list[dict] = []
    for w in windows:
        for sv in w.state_vars:
            name = sv.get("getter", "")
            if not name:
                continue
            if any(o.get("getter") == name for o in out):
                continue
            out.append(sv)
    return out


def collect_cpp_imports(windows) -> list[dict]:
    """Deduplicated user C++ imports across all windows.

    Returns [{"path": "/abs/path/native.cpp", "specifiers": [...],
              "import_path": "./native.cpp"}, ...]
    """
    out: list[dict] = []
    seen: set[str] = set()
    for w in windows:
        for ci in w.cpp_imports:
            key = ci.get("path", "")
            if not key or key in seen:
                continue
            seen.add(key)
            out.append(ci)
    return out


# ── Function signature extraction from transpiled C++ ──


def extract_function_decl(cpp: str) -> str | None:
    """Extract `ret name(params);` from transpiled C++ like
    `static inline\\nvoid increment() { ... }`.

    Returns None for non-function declarations (global vars etc.). Skips
    `main` (the app defines its own entry point).
    """
    text = cpp.strip()
    if not text:
        return None

    # Preserve any template prefix, e.g. "template <typename T>"
    tpl = ""
    while text.startswith("template") and ">" in text:
        end = text.find(">")
        if end == -1:
            return None
        tpl = text[: end + 1]
        text = text[end + 1 :].strip()

    # Strip linkage qualifiers
    text = re.sub(r"^(static\s+inline\s+|static\s+|inline\s+)", "", text)

    # Find the opening brace at paren-depth 0 (function body start).
    depth = 0
    for i, ch in enumerate(text):
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        elif ch == "{" and depth == 0:
            header = text[:i].rstrip()
            if "(" not in header or ")" not in header:
                return None
            # Skip `main` — the app provides its own.
            m = re.search(r"\bmain\s*\(", header)
            if m:
                return None
            return f"{tpl}\n{header};".strip() if tpl else f"{header};"
    return None


def strip_static_function(cpp: str) -> str:
    """Remove `static inline`/`static` linkage from a function declaration
    so it gets external linkage (visible to user .cpp code)."""
    text = cpp.strip()
    return re.sub(r"^(static\s+inline\s+|static\s+)", "", text, count=1)


# ── Generated header ──


def generate_state_header(windows, state_decls: list[dict],
                          premain_parts: list[str]) -> str:
    """Build the `_morph_state.h` content.

    Exposes (all `extern`, defined in the generated TU):
      - morphState signals: `__st_<name>`
      - JSX-style wrappers: `set<Name>(v)` / `get<Name>()`
      - JSX functions:      `<ret> <name>(<params>);`
    """
    lines = [
        "#pragma once",
        "// Generated by Morph — do not edit",
        '#include "morph_api.h"',
        "",
    ]

    # ── Extern signals + wrappers ──
    # Wrapper names must not collide with JSX functions the user defined.
    jsx_names: set[str] = set()
    for part in premain_parts:
        decl = extract_function_decl(part)
        if decl:
            m = re.search(r"([A-Za-z_$][\w$]*)\s*\(", decl)
            if m:
                jsx_names.add(m.group(1))

    sig_decls: dict[str, str] = {}
    for sv in state_decls:
        name = sv.get("signal_name", "")
        if not name:
            continue
        sig_decls[name] = sv.get("type", "auto")

    if sig_decls:
        lines.append("// ── morphState signals (defined in the generated TU) ──")
        for sig, cpp_type in sig_decls.items():
            lines.append(f"extern morph::Signal<{cpp_type}> {sig};")
        lines.append("")
        lines.append("// ── JSX state wrappers — call from C++ like setState() ──")
        for sig, cpp_type in sig_decls.items():
            base = sig[len("__st_") :] if sig.startswith("__st_") else sig
            getter = base
            setter = "set" + base[:1].upper() + base[1:]
            if getter not in jsx_names:
                lines.append(f"inline {cpp_type} {getter}() {{ return {sig}.get(); }}")
            if setter not in jsx_names:
                lines.append(
                    f"inline void {setter}({cpp_type} v) {{ {sig}.set(v); }}")
        lines.append("")

    # ── JSX function declarations ──
    func_decls: list[str] = []
    seen: set[str] = set()
    for part in premain_parts:
        decl = extract_function_decl(part)
        if decl and decl not in seen:
            seen.add(decl)
            func_decls.append(decl)
    if func_decls:
        lines.append("// ── JSX functions (defined in the generated TU) ──")
        lines.extend(func_decls)
        lines.append("")

    return "\n".join(lines)