use anyhow::Result;
use morph_ir::{IRWindow, IRNode};
use std::path::Path;

use crate::FeatureSet;

pub struct CppEmitter<'a> {
    windows: &'a [IRWindow],
    features: FeatureSet,
}

impl<'a> CppEmitter<'a> {
    pub fn new(windows: &'a [IRWindow]) -> Self {
        Self {
            windows,
            features: FeatureSet::scan(windows),
        }
    }

    pub fn emit(&self, output_dir: &Path) -> Result<()> {
        std::fs::create_dir_all(output_dir)?;

        let mut cpp = String::new();

        // Header
        cpp.push_str("// Auto-generated by morphc — do not edit.\n");
        cpp.push_str("#include \"runtime/cpp/dev/logic_prelude.h\"\n");
        for header in self.features.required_headers() {
            cpp.push_str(&format!("#include \"{header}\"\n"));
        }
        cpp.push('\n');

        // Feature defines
        for define in self.features.required_defines() {
            cpp.push_str(&format!("#define {define}\n"));
        }
        cpp.push('\n');

        // Window creation and node emission
        for (i, window) in self.windows.iter().enumerate() {
            self.emit_window(&mut cpp, window, i);
        }

        std::fs::write(output_dir.join("app.cpp"), cpp)?;
        Ok(())
    }

    fn emit_window(&self, cpp: &mut String, window: &IRWindow, index: usize) {
        let w_id = format!("w{index}");

        cpp.push_str(&format!("// ── Window: \"{}\" ({}x{}) ──\n", window.title, window.width, window.height));
        cpp.push_str(&format!("static morph::Window {w_id}({},{},\"{}\");\n",
            window.width, window.height, window.title));
        cpp.push_str(&format!("{w_id}.set_visible({});\n", window.visible));

        if let Some(min_w) = window.min_width {
            cpp.push_str(&format!("{w_id}.set_min_size({},{});\n", min_w, window.min_height.unwrap_or(min_w)));
        }

        cpp.push('\n');

        // Emit nodes
        for node in &window.nodes {
            self.emit_node(cpp, node, &w_id);
        }

        cpp.push_str(&format!("{w_id}.show();\n"));
        cpp.push('\n');
    }

    fn emit_node(&self, cpp: &mut String, node: &IRNode, parent: &str) {
        if !node.condition_expr.is_empty() {
            self.emit_conditional(cpp, node, parent);
            return;
        }
        if !node.list_expr.is_empty() {
            self.emit_list(cpp, node, parent);
            return;
        }

        let node_id = &node.node_id;

        match node.node_type.as_str() {
            "text" | "__text__" => {
                let escaped = escape_cpp_string(&node.text_content);
                cpp.push_str(&format!("auto {node_id} = {parent}.add_text(\"{escaped}\");\n"));
            }
            "button" => {
                cpp.push_str(&format!("auto {node_id} = {parent}.add_button();\n"));
                if !node.text_content.is_empty() {
                    let escaped = escape_cpp_string(&node.text_content);
                    cpp.push_str(&format!("{node_id}->set_text(\"{escaped}\");\n"));
                }
            }
            "input" => {
                cpp.push_str(&format!("auto {node_id} = {parent}.add_input();\n"));
                if let Some(placeholder) = node.attrs.get("placeholder") {
                    let escaped = escape_cpp_string(placeholder);
                    cpp.push_str(&format!("{node_id}->set_placeholder(\"{escaped}\");\n"));
                }
            }
            "img" => {
                cpp.push_str(&format!("auto {node_id} = {parent}.add_image();\n"));
                if let Some(src) = node.attrs.get("src") {
                    let escaped = escape_cpp_string(src);
                    cpp.push_str(&format!("{node_id}->set_src(\"{escaped}\");\n"));
                }
            }
            _ => {
                // Rect container (div, section, etc.)
                cpp.push_str(&format!("auto {node_id} = {parent}.add_rect();\n"));
            }
        }

        // Emit style
        self.emit_style(cpp, node, node_id);

        // Emit children
        for child in &node.children {
            self.emit_node(cpp, child, node_id);
        }
    }

    fn emit_style(&self, cpp: &mut String, node: &IRNode, node_id: &str) {
        let s = &node.style;

        if s.bg_color[3] > 0.0 {
            cpp.push_str(&format!("{node_id}->set_bg_color({},{},{},{});\n",
                s.bg_color[0], s.bg_color[1], s.bg_color[2], s.bg_color[3]));
        }
        if s.color != [0.0, 0.0, 0.0, 1.0] {
            cpp.push_str(&format!("{node_id}->set_color({},{},{},{});\n",
                s.color[0], s.color[1], s.color[2], s.color[3]));
        }
        if let Some(w) = s.width {
            cpp.push_str(&format!("{node_id}->set_width({w});\n"));
        }
        if let Some(h) = s.height {
            cpp.push_str(&format!("{node_id}->set_height({h});\n"));
        }
        if s.border_radius > 0.0 {
            cpp.push_str(&format!("{node_id}->set_radius({});\n", s.border_radius));
        }
        if s.font_size != 16.0 {
            cpp.push_str(&format!("{node_id}->set_font_size({});\n", s.font_size));
        }
        if s.padding != [0.0, 0.0, 0.0, 0.0] {
            cpp.push_str(&format!("{node_id}->set_padding({},{},{},{});\n",
                s.padding[0], s.padding[1], s.padding[2], s.padding[3]));
        }
        if s.display != "block" {
            cpp.push_str(&format!("{node_id}->set_display(\"{}\");\n", s.display));
        }
        if s.opacity < 1.0 {
            cpp.push_str(&format!("{node_id}->set_opacity({});\n", s.opacity));
        }
    }

    fn emit_conditional(&self, cpp: &mut String, node: &IRNode, parent: &str) {
        let node_id = &node.node_id;
        let cond = &node.condition_expr;
        cpp.push_str(&format!("if ({cond}) {{\n"));
        for child in &node.then_nodes {
            self.emit_node(cpp, child, parent);
        }
        if !node.else_nodes.is_empty() {
            cpp.push_str("} else {\n");
            for child in &node.else_nodes {
                self.emit_node(cpp, child, parent);
            }
        }
        cpp.push_str("}\n");
    }

    fn emit_list(&self, cpp: &mut String, node: &IRNode, parent: &str) {
        // Stub: list rendering
        cpp.push_str(&format!("// TODO: list container for {}\n", node.node_id));
    }
}

fn escape_cpp_string(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}
