[package]
name = "morph-ir"
version = "0.1.0"
edition = "2021"
description = "Morph Intermediate Representation"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
morph-parser = { path = "../morph-parser" }
morpher = { path = "../morpher" }
oxc_allocator = { workspace = true }
oxc_ast = { workspace = true }
oxc_parser = { workspace = true }
oxc_span = { workspace = true }

[lints]
workspace = true
